@startuml
left to right direction

:Konsument: as act01

rectangle "Einkaus App" {
    "UC01\nEinkaufsliste erstellen" as (uc01)
    "UC02\nEinkaufsliste im\nSupermarkt abarbeiten" as (uc02)
}

act01 -- (uc01)
act01 -- (uc02)
@enduml
